### ISSUE TITLE
`[no-unlocalized-strings]` Tracking issue for the rule improvements. 

### ISSUE THREAD

**Issue by timofei-iatsenko** [lingui/eslint-plugin#50]
I created this issue to collect all problems / improvements for `no-unlocalized-strings` rule. 

- [x] Support regexp in  `ignoreAttribute`  `ignoreProperty` `ignoreFunction`  https://github.com/lingui/eslint-plugin/issues/40
- [ ] Ignore subkeys with `ignoreProperty` https://github.com/lingui/eslint-plugin/issues/39
- [x] ignore bracket access strings by default, eq `obj["key with space”]` https://github.com/lingui/eslint-plugin/issues/38
- [x] use type information to ignore methods from some popular built-ins such as `Map`, `Set`, etc https://github.com/lingui/eslint-plugin/issues/38
- [x] `ignoreProperty` should work for `ClassDeclaration -> PropertyDefinition`, `ObjectExpression -> Property`, `MemberExpression.property` https://github.com/lingui/eslint-plugin/issues/37
- [x] The original whitelist regexp works a bit weird, need refinement https://github.com/lingui/eslint-plugin/issues/30

**Comment by jgarplind** [comment]
Not sure if this is a good place to share input, but we noticed that `const CAPITAL_LETTERS` is always ignored(?).

Might be an anti-pattern on our end, but we have occasionally used such syntax for copy text, which the linter did not help us catch.

**Comment by timofei-iatsenko** [comment]
Yes, this excluded by default. The capital letters in the variable names mostly used to define constants, so they are excluded.  

I think it could be a good idea to revisit the defaults, and make them configurable or overridable.

**Comment by nyadav810** [comment]
Any chance that regex patterns will be supported in `ignoreFunction` in the future? I want to be able to ignore `Events.*`, `logger.*` and `console.*` with all functions exposed on a certain object ignored by this rule. Thanks!

**Comment by timofei-iatsenko** [comment]
@nyadav810 `ignoreFunction` is a little bit different from other `ignore*` options, because `ignoreFunction` supports complex selectors matching `object.method`, which in AST is presented as different nodes, so the signature for this option is not trivial.

**Comment by timofei-iatsenko** [comment]
I went through the issues with this rule and tried to address them all. It seems like we need a big change in how the rule is set up. There’s no way to make it work perfectly for everyone and every project. So, I’ve decided to remove all the built-in settings and made them fully customizable.

For example, if a user doesn’t want:

> but we noticed that const CAPITAL_LETTERS is always ignored(?).

they can simply remove the related regex from their options.

Let me know what you think, and feel free to share any other feedback you have on this rule.

**Comment by jgarplind** [comment]
I think the defaults so far have been very sane, and only small caveats such as the above have been slight nuissences.

As long as it is easy to reproduce the existing default experience, I think that sounds good!

**Comment by timofei-iatsenko** [comment]
@nyadav810 FYI https://github.com/lingui/eslint-plugin/pull/77

**Comment by timofei-iatsenko** [comment]
Guys, I would appreciate if you review and left your feedback on this PR https://github.com/lingui/eslint-plugin/pull/78

Also while working on it, i've noticed that in a real life sceanario we probably don't need separate settings for `ignoreAttribute`, `ignoreProperties`, `ignoreVariable` because in most of the cases we will want to have the same values in all of them. And now i'm thinking of replacing all these 3 options into one.  

```js
/* eslint lingui/no-unlocalized-strings: ["error", {"ignoreAttribute": ["className"]}] */
export const MyComponent() {
 return <div className="classes string">Ola!</>
}
```

```js
/* eslint lingui/no-unlocalized-strings: ["error", {"ignoreVariable": ["className"]}] */
export const MyComponent() {
  const className = "doing some magic";

 return <div className={className}>Ola!</>
}
```

```js
/* eslint lingui/no-unlocalized-strings: ["error", {"ignoreProperty": ["className"]}] */
const variants = {
  variantA: {
    className: "classes string"
  },
  variantB: {
    className: "classes string"
  }
]
export const MyComponent({variant}) {
 return <div className={variants[variant].className}>Ola!</>
}

**Comment by nyadav810** [comment]
Thanks for the improvements @timofei-iatsenko !!!

Another quirk I found - when called as a function, `msg` triggers this warning as well!

Example:

``` 
msg({ message: "hello", comment: "a common greeting" })

...
warning  String not marked for translation. Wrap it with t``, <Trans>, or msg``  lingui/no-unlocalized-strings
```

**Comment by timofei-iatsenko** [comment]
@nyadav810 thanks for the report. Also noticed it when worked on the #78. It's fixed there.
